# Generated by Django 4.2.4 on 2023-12-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("name", models.CharField(blank=True, max_length=20)),
                ("roll", models.IntegerField(blank=True)),
                ("city", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ModelB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("subject", models.CharField(blank=True, max_length=20)),
                ("sport", models.CharField(blank=True, max_length=20)),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FK_MODELA_TO_B",
                        to="api.modela",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="modela",
            index=models.Index(fields=["roll"], name="api_modela_roll_910fd0_idx"),
        ),
    ]
